=== llol252t/Baimuratov-Azat-PIN252t/dtd-document.dtd
<!-- University.dtd -->

<!ELEMENT University (info, Rectorate)>

<!ELEMENT info (title, fullName, website)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT fullName (#PCDATA)>
<!ELEMENT website (#PCDATA)>

<!ELEMENT Rectorate (info, rector, pro-rectors)>

<!ELEMENT rector (firstname, patronymic, surname, academicTitle?, academicDegree, position, image)>
<!ELEMENT pro-rectors (pro-rector+)>

<!ELEMENT pro-rector (firstname, patronymic, surname, academicTitle?, academicDegree?, position, image)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT patronymic (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT academicTitle (#PCDATA)>
<!ELEMENT academicDegree (#PCDATA)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT image EMPTY>

<!-- Атрибуты -->
<!ATTLIST pro-rector id ID #REQUIRED>
<!ATTLIST image src CDATA #REQUIRED>

=== llol252t/Baimuratov-Azat-PIN252t/xml-document.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl-document.xsl"?>
<!DOCTYPE University SYSTEM "dtd-document.dtd">
<University xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="xsd-document.xsd">
    <info>
        <!--Название университета-->
        <title>Руководство ОмГТУ</title>
        <fullName>Омский государственный технический университет</fullName>
        <website>https://omgtu.ru/general_information/guide_omgtu/</website>
    </info>
    
    <Rectorate>
        <info>  
            <!--Ректорат ОмГТУ--> 
            <title>Ректорат</title>
            <fullName></fullName>
            <website></website>
        </info>
        
        <rector>
            <!--Ректор ОмГТУ-->
            <firstname>Павел</firstname>
            <patronymic>Александрович</patronymic> 
            <surname>Корчагин</surname> 
            <academicTitle>профессор</academicTitle>
            <academicDegree>д.т.н</academicDegree>  
            <position>Ректор</position> 
            <image src="https://omgtu.ru/general_information/guide_omgtu/%D0%9A%D0%BE%D1%80%D1%87%D0%B0%D0%B3%D0%B8%D0%BD.jpg"/> 
        </rector>
        
        <pro-rectors>
            <!--Про-ректор по образовательной деятельности-->
            <pro-rector id="1">   
                <firstname>Наталья</firstname>   
                <patronymic>Анатольевна</patronymic>   
                <surname>Прокудина</surname> 
                <academicTitle>доцент</academicTitle> 
                <academicDegree>к.т.н</academicDegree>   
                <position>Проректор по образовательной деятельности</position> 
                <image src="https://omgtu.ru/general_information/guide_omgtu/rectorate-photo/%D0%9F%D1%80%D0%BE%D0%BA%D1%83%D0%B4%D0%B8%D0%BD%D0%B0.jpg"/>   
            </pro-rector> 
            
            <pro-rector id="2">
                <!--Про-ректор по научной и инновационной деятельности--> 
                <firstname>Павел</firstname>   
                <patronymic>Сергеевич</patronymic>   
                <surname>Ложников</surname>   
                <academicTitle>доцент</academicTitle> 
                <academicDegree>д.т.н</academicDegree> 
                <position>Проректор по научной и инновационной деятельности</position>   
                <image src="https://omgtu.ru/general_information/guide_omgtu/rectorate-photo/%D0%9B%D0%BE%D0%B6%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2.jpg"/>   
            </pro-rector> 
            
            <pro-rector id="3">  
                <!--Про-ректор по молодежной политике и воспитательной деятельности--> 
                <firstname>Олег</firstname>   
                <patronymic>Александрович</patronymic>   
                <surname>Перегудов</surname> 
                <academicTitle>доцент</academicTitle>
                <academicDegree>к.т.н</academicDegree> 
                <position>Проректор по молодежной политике и воспитательной деятельности</position>
                <image src="https://omgtu.ru/general_information/guide_omgtu/rectorate-photo/%D0%9F%D0%B5%D1%80%D0%B5%D0%B3%D1%83%D0%B4%D0%BE%D0%B2.jpg"/>   
            </pro-rector> 
            
            <pro-rector id="4">   
                <!--Про-ректор по цифровой трансформации-->
                <firstname>Александр</firstname>   
                <patronymic>Сергеевич</patronymic>   
                <surname>Грицай</surname>   
                <academicTitle>доцент</academicTitle> 
                <academicDegree>к.т.н</academicDegree> 
                <position>Проректор по цифровой трансформации</position>   
                <image src="https://omgtu.ru/general_information/guide_omgtu/rectorate-photo/%D0%93%D1%80%D0%B8%D1%86%D0%B0%D0%B9.jpg"/>   
            </pro-rector> 
        </pro-rectors> 
    </Rectorate> 
</University>
